stages:
  - download
  - build
  - test

dl-deps:
  stage: download
  tags:
    - pira
  script: 
    - git submodule init;
    - git submodule update extern/src/cgcollector;
    - git submodule update extern/src/llvm-instrumenter;
    - git submodule update extern/src/scorep-mod;

build-deps:
  stage: build
  tags:
    - pira
  script:
    - git submodule init;
    - git submodule update extern/src/cgcollector;
    - git submodule update extern/src/llvm-instrumenter;
    - git submodule update extern/src/scorep-mod;
    - ls ./extern/src/llvm-instrumenter
    - module use /opt/modules/modulefiles
    - module load clang/9
    - echo $PATH
    - cd resources
    - ./build_submodules.sh 6 --without-mpi
